def fun1(l,c):
	if l=='ర':
		if c=='ర':
			return 'ర్ర'
		if c=='క':
			return 'ర్క'
		if c=='య':
			return 'ర్య'
		return 'ర'
	if l=='క':
		if c=='ర':
			return 'క్ర'
		if c=='క':
			return 'క్క'
		if c=='య':
			return 'క్య'
		return 'క'
	if l=='య':
		if c=='ర':
			return 'య్ర'
		if c=='క':
			return 'య్క'
		if c=='య':
			return 'య్య'
		return 'య'
def fun2(l,v,c):
	if c=='ర':
		if l=='ర్ర':
			if v=='ఆ':
				return 'ర్రా'
			if v=='ఇ':
				return 'ర్రి'
			if v=='ఈ':
				return 'ర్రీ'
			if v=='ఉ':
				return 'ర్రు'
			if v=='ఊ':
				return 'ర్రూ'
			if v=='ఋ':
				return 'ర్రృ'
			if v=='ౠ':
				return 'ర్రౄ'
			if v=='ఎ':
				return 'ర్రె'
			if v=='ఏ':
				return 'ర్రే'
			if v=='ఐ':
				return 'ర్రై'
			if v=='ఒ':
				return 'ర్రొ'
			if v=='ఓ':
				return 'ర్రో'
			if v=='ఔ':
				return 'ర్రౌ'
			if v=='అం':
				return 'ర్రం'
			if v=='అః':
				return 'ర్రః'
			return 'ర్ర'
		if l=='ర్క':
			if v=='ఆ':
				return 'ర్కా'
			if v=='ఇ':
				return 'ర్కి'
			if v=='ఈ':
				return 'ర్కీ'
			if v=='ఉ':
				return 'ర్కు'
			if v=='ఊ':
				return 'ర్కూ'
			if v=='ఋ':
				return 'ర్కృ'
			if v=='ౠ':
				return 'ర్కౄ'
			if v=='ఎ':
				return 'ర్కె'
			if v=='ఏ':
				return 'ర్కే'
			if v=='ఐ':
				return 'ర్కై'
			if v=='ఒ':
				return 'ర్కొ'
			if v=='ఓ':
				return 'ర్కో'
			if v=='ఔ':
				return 'ర్కౌ'
			if v=='అం':
				return 'ర్కం'
			if v=='అః':
				return 'ర్కః'
			return 'ర్క'
		if l=='ర్య':
			if v=='ఆ':
				return 'ర్యా'
			if v=='ఇ':
				return 'ర్యి'
			if v=='ఈ':
				return 'ర్యీ'
			if v=='ఉ':
				return 'ర్యు'
			if v=='ఊ':
				return 'ర్యూ'
			if v=='ఋ':
				return 'ర్యృ'
			if v=='ౠ':
				return 'ర్యౄ'
			if v=='ఎ':
				return 'ర్యె'
			if v=='ఏ':
				return 'ర్యే'
			if v=='ఐ':
				return 'ర్యై'
			if v=='ఒ':
				return 'ర్యొ'
			if v=='ఓ':
				return 'ర్యో'
			if v=='ఔ':
				return 'ర్యౌ'
			if v=='అం':
				return 'ర్యం'
			if v=='అః':
				return 'ర్యః'
			return 'ర్య'
	if c=='క':
		if l=='క్ర':
			if v=='ఆ':
				return 'క్రా'
			if v=='ఇ':
				return 'క్రి'
			if v=='ఈ':
				return 'క్రీ'
			if v=='ఉ':
				return 'క్రు'
			if v=='ఊ':
				return 'క్రూ'
			if v=='ఋ':
				return 'క్రృ'
			if v=='ౠ':
				return 'క్రౄ'
			if v=='ఎ':
				return 'క్రె'
			if v=='ఏ':
				return 'క్రే'
			if v=='ఐ':
				return 'క్రై'
			if v=='ఒ':
				return 'క్రొ'
			if v=='ఓ':
				return 'క్రో'
			if v=='ఔ':
				return 'క్రౌ'
			if v=='అం':
				return 'క్రం'
			if v=='అః':
				return 'క్రః'
			return 'క్ర'
		if l=='క్క':
			if v=='ఆ':
				return 'క్కా'
			if v=='ఇ':
				return 'క్కి'
			if v=='ఈ':
				return 'క్కీ'
			if v=='ఉ':
				return 'క్కు'
			if v=='ఊ':
				return 'క్కూ'
			if v=='ఋ':
				return 'క్కృ'
			if v=='ౠ':
				return 'క్కౄ'
			if v=='ఎ':
				return 'క్కె'
			if v=='ఏ':
				return 'క్కే'
			if v=='ఐ':
				return 'క్కై'
			if v=='ఒ':
				return 'క్కొ'
			if v=='ఓ':
				return 'క్కో'
			if v=='ఔ':
				return 'క్కౌ'
			if v=='అం':
				return 'క్కం'
			if v=='అః':
				return 'క్కః'
			return 'క్క'
		if l=='క్య':
			if v=='ఆ':
				return 'క్యా'
			if v=='ఇ':
				return 'క్యి'
			if v=='ఈ':
				return 'క్యీ'
			if v=='ఉ':
				return 'క్యు'
			if v=='ఊ':
				return 'క్యూ'
			if v=='ఋ':
				return 'క్యృ'
			if v=='ౠ':
				return 'క్యౄ'
			if v=='ఎ':
				return 'క్యె'
			if v=='ఏ':
				return 'క్యే'
			if v=='ఐ':
				return 'క్యై'
			if v=='ఒ':
				return 'క్యొ'
			if v=='ఓ':
				return 'క్యో'
			if v=='ఔ':
				return 'క్యౌ'
			if v=='అం':
				return 'క్యం'
			if v=='అః':
				return 'క్యః'
			return 'క్య'
	if c=='య':
		if l=='య్ర':
			if v=='ఆ':
				return 'య్రా'
			if v=='ఇ':
				return 'య్రి'
			if v=='ఈ':
				return 'య్రీ'
			if v=='ఉ':
				return 'య్రు'
			if v=='ఊ':
				return 'య్రూ'
			if v=='ఋ':
				return 'య్రృ'
			if v=='ౠ':
				return 'య్రౄ'
			if v=='ఎ':
				return 'య్రె'
			if v=='ఏ':
				return 'య్రే'
			if v=='ఐ':
				return 'య్రై'
			if v=='ఒ':
				return 'య్రొ'
			if v=='ఓ':
				return 'య్రో'
			if v=='ఔ':
				return 'య్రౌ'
			if v=='అం':
				return 'య్రం'
			if v=='అః':
				return 'య్రః'
			return 'య్ర'
		if l=='య్క':
			if v=='ఆ':
				return 'య్కా'
			if v=='ఇ':
				return 'య్కి'
			if v=='ఈ':
				return 'య్కీ'
			if v=='ఉ':
				return 'య్కు'
			if v=='ఊ':
				return 'య్కూ'
			if v=='ఋ':
				return 'య్కృ'
			if v=='ౠ':
				return 'య్కౄ'
			if v=='ఎ':
				return 'య్కె'
			if v=='ఏ':
				return 'య్కే'
			if v=='ఐ':
				return 'య్కై'
			if v=='ఒ':
				return 'య్కొ'
			if v=='ఓ':
				return 'య్కో'
			if v=='ఔ':
				return 'య్కౌ'
			if v=='అం':
				return 'య్కం'
			if v=='అః':
				return 'య్కః'
			return 'య్క'
		if l=='య్య':
			if v=='ఆ':
				return 'య్యా'
			if v=='ఇ':
				return 'య్యి'
			if v=='ఈ':
				return 'య్యీ'
			if v=='ఉ':
				return 'య్యు'
			if v=='ఊ':
				return 'య్యూ'
			if v=='ఋ':
				return 'య్యృ'
			if v=='ౠ':
				return 'య్యౄ'
			if v=='ఎ':
				return 'య్యె'
			if v=='ఏ':
				return 'య్యే'
			if v=='ఐ':
				return 'య్యై'
			if v=='ఒ':
				return 'య్యొ'
			if v=='ఓ':
				return 'య్యో'
			if v=='ఔ':
				return 'య్యౌ'
			if v=='అం':
				return 'య్యం'
			if v=='అః':
				return 'య్యః'
			return 'య్య'